# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Merqueo_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Merqueo_test

  target 'Merqueo_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Merqueo_testUITests' do
    # Pods for testing
  end

end
